name: Sync 'iptv-api/output' directory to dest-repo: myedgehtml/iptv

on:
  push:
    branches:
      - main # 只有当 main 分支有更新时才触发
    paths:
      - 'output/**' # 只有当 output 目录下的文件发生变化时才触发，提高效率

  workflow_dispatch: # 允许手动触发此工作流

jobs:
  push-to-dest-repo:
    runs-on: ubuntu-latest
    steps:
      # 第 1 步：检出 source-repo 的代码
      - name: Checkout source-repo
        uses: actions/checkout@v4

      # 第 2 步：将 'output' 目录推送到 dest-repo
      - name: Push 'output' directory to dest-repo
        uses: cpina/github-action-push-to-another-repo@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACTIONS_PAT }} # 使用我们刚刚创建的 Secret
        with:
          source-directory: 'output' # 要同步的源目录
          destination-github-username: '<your-github-username>' # 目标仓库的拥有者（你的用户名或组织名）
          destination-repository-name: 'dest-repo' # 目标仓库的名称
          user-email: 'actions@github.com' # 提交者邮箱
          user-name: 'GitHub Actions' # 提交者名称
          commit-message: 'Automated sync from source-repo' # 自定义 Git 提交信息
          target-branch: 'main' # 要推送到目标仓库的哪个分支
